#!/usr/bin/env ruby
# frozen_string_literal: true

if ARGV[0] == "component"
  require "decidim/generators/component_generator"

  Decidim::Generators::ComponentGenerator.start
else
  require "decidim/generators/app_generator"

  Decidim::Generators::AppGenerator.start
end
